# This workflow will build a Java project with Maven, and cache/restore dependencies to improve execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      

      - name: Install Chrome & ChromeDriver
        run: |
          
          sudo apt-get update 
          sudo apt-get install -y chromium-chromedriver
          sudo apt-get install -y google-chrome-stable          
           google-chrome --version
           chromedriver --version
      - name: Debug Chrome & ChromeDriver
        run: |
           google-chrome --version
           chromedriver --version
           which chromedriver
      
      - name: Build with Maven
        run: cd GitIntegration && mvn clean test -B package --file pom.xml

  
